import { useState } from "react";
import axios from "axios";

export default function Home() {
  const [text, setText] = useState("");
  const [tool, setTool] = useState("grammar");
  const [result, setResult] = useState("");
  const [provider, setProvider] = useState("");
  const [loading, setLoading] = useState(false);
  const [history, setHistory] = useState([]);

  const tools = [
    { id: "grammar", name: "Grammar Checker" },
    { id: "meaning", name: "Word Meaning" },
    { id: "paraphrase", name: "Paraphraser" },
    { id: "vocabulary", name: "Vocabulary Builder" },
    { id: "essay", name: "Essay Evaluator" },
  ];

  const handleSubmit = async () => {
    if (!text.trim()) return;

    setLoading(true);
    setResult("");

    try {
      const res = await axios.post("http://localhost:5000/api/ai/analyze", {
        tool,
        text,
      });

      setResult(res.data.result);
      setProvider(res.data.provider);

      setHistory([
        {
          tool,
          text,
          result: res.data.result,
        },
        ...history,
      ]);
    } catch (error) {
      console.log(error.response?.data || error.message);
    }

    setLoading(false);
  };

  return (
    <div className="min-h-screen bg-gray-100 flex flex-col items-center py-10">
      <h1 className="text-4xl font-bold mb-8">FluentAI Prep</h1>

      {/* TOOL CARDS */}

      <div className="grid grid-cols-2 gap-4 mb-8">
        {tools.map((t) => (
          <button
            key={t.id}
            onClick={() => setTool(t.id)}
            className={`p-4 rounded-lg border text-left ${
              tool === t.id
                ? "bg-blue-600 text-white"
                : "bg-white hover:bg-gray-50"
            }`}
          >
            {t.name}
          </button>
        ))}
      </div>

      {/* INPUT */}

      <textarea
        className="w-[600px] border p-4 rounded mb-4"
        rows="4"
        placeholder="Enter text..."
        value={text}
        onChange={(e) => setText(e.target.value)}
      />

      <button
        onClick={handleSubmit}
        className="bg-blue-600 text-white px-6 py-2 rounded"
      >
        {loading ? "Analyzing..." : "Analyze"}
      </button>

      {/* RESULT */}

      {result && (
        <div className="w-[600px] mt-8 bg-white border rounded-lg p-6 shadow">
          <p className="text-sm text-gray-500 mb-4">
            Generated by {provider} ⚡
          </p>

          {result.split("\n\n").map((section, i) => (
            <div key={i} className="mb-4">
              {section.includes("Correct Sentence") && (
                <>
                  <h3 className="font-semibold text-green-600">
                    Correct Sentence
                  </h3>
                  <p>{section.replace("Correct Sentence:", "")}</p>
                </>
              )}

              {section.includes("Explanation") && (
                <>
                  <h3 className="font-semibold text-blue-600">Explanation</h3>
                  <p>{section.replace("Explanation:", "")}</p>
                </>
              )}

              {section.includes("Grammar Rule") && (
                <>
                  <h3 className="font-semibold text-purple-600">
                    Grammar Rule
                  </h3>
                  <p>{section.replace("Grammar Rule:", "")}</p>
                </>
              )}
            </div>
          ))}
        </div>
      )}

      {/* HISTORY */}

      {history.length > 0 && (
        <div className="w-[600px] mt-8">
          <h2 className="text-xl font-semibold mb-4">Recent Analyses</h2>

          {history.map((item, index) => (
            <div
              key={index}
              className="bg-white border p-4 rounded mb-3 shadow-sm"
            >
              <p className="text-sm text-gray-500">Tool: {item.tool}</p>

              <p className="font-medium">Input: {item.text}</p>

              <p className="text-sm mt-2 text-gray-700 line-clamp-3">
                {item.result}
              </p>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
