import dotenv from "dotenv";
dotenv.config();

import { GoogleGenerativeAI } from "@google/generative-ai";
import Groq from "groq-sdk";
import OpenAI from "openai";

const GEMINI_KEY = process.env.GEMINI_API_KEY;
const GROQ_KEY = process.env.GROQ_API_KEY;
const OPENAI_KEY = process.env.OPENAI_API_KEY;

console.log("Gemini key:", GEMINI_KEY ? "Loaded" : "Missing");
console.log("Groq key:", GROQ_KEY ? "Loaded" : "Missing");
console.log("OpenAI key:", OPENAI_KEY ? "Loaded" : "Missing");

const gemini = GEMINI_KEY ? new GoogleGenerativeAI(GEMINI_KEY) : null;

const groq = GROQ_KEY
  ? new Groq({
      apiKey: GROQ_KEY
    })
  : null;

const openai = OPENAI_KEY
  ? new OpenAI({
      apiKey: OPENAI_KEY
    })
  : null;

export const askAI = async (prompt) => {

  // 1️⃣ Gemini
  if (gemini) {
    try {

      const model = gemini.getGenerativeModel({
        model: "gemini-1.5-flash"
      });

      const result = await model.generateContent(prompt);

      const text = result.response.text();

      if (text) {
        console.log("Response generated by Gemini");
        return {
          provider: "Gemini",
          text
        };
      }

    } catch (err) {
      console.log("Gemini failed:", err.message);
    }
  }

  // 2️⃣ Groq
  if (groq) {
    try {

      const chat = await groq.chat.completions.create({
        model: "llama-3.1-8b-instant",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      });

      const text = chat.choices?.[0]?.message?.content;

      if (text) {
        console.log("Response generated by Groq");
        return {
          provider: "Groq",
          text
        };
      }

    } catch (err) {
      console.log("Groq failed:", err.message);
    }
  }

  // 3️⃣ OpenAI
  if (openai) {
    try {

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini",
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      });

      const text = completion.choices?.[0]?.message?.content;

      if (text) {
        console.log("Response generated by OpenAI");
        return {
          provider: "OpenAI",
          text
        };
      }

    } catch (err) {
      console.log("OpenAI failed:", err.message);
    }
  }

  throw new Error("All AI providers failed");

};